name: Generate Release 3

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select the target branch'
        required: true
        default: 'main'
        type: string

env:
  TZ: America/Phoenix

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Set Report Date Time
        id: datetime
        run: echo "DATESTAMP=$(date +"%Y-%m-%d")" >> "$GITHUB_OUTPUT"

      - name: Fetch merged PRs
        id: fetch_prs
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.inputs.target_branch }}';
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: branch,
              per_page: 100
            });

            const mergedPRs = prs.filter(pr => pr.merged_at);
            const formatted = mergedPRs.map(pr => ({
              number: pr.number,
              title: pr.title,
              user: pr.user.login,
              merged_at: pr.merged_at,
              html_url: pr.html_url,
              issue_key: pr.title.match(/NCX-\d+/)?.[0] ?? ''
            }));

            core.setOutput("pr_data", JSON.stringify(formatted));

      - name: Display Release Notes in Console
        run: |
          echo ""
          echo "📄 Release Notes - ${{ steps.datetime.outputs.DATESTAMP }}"
          echo "Target Branch: ${{ github.event.inputs.target_branch }}"
          echo ""
          echo "## 🚀 Merged Pull Requests"
          echo "| PR | Title | Author | Merged Date | Issue Key |"
          echo "|----|-------|--------|-------------|-----------|"

          echo '${{ steps.fetch_prs.outputs.pr_data }}' | jq -c '.[]' | while read pr; do
            NUMBER=$(echo "$pr" | jq -r '.number')
            TITLE=$(echo "$pr" | jq -r '.title' | sed 's/|/\\|/g')
            USER=$(echo "$pr" | jq -r '.user')
            MERGED=$(echo "$pr" | jq -r '.merged_at' | cut -d"T" -f1)
            URL=$(echo "$pr" | jq -r '.html_url')
            ISSUE=$(echo "$pr" | jq -r '.issue_key')
            echo "| [#$NUMBER]($URL) | $TITLE | @$USER | $MERGED | $ISSUE |"
          done
