name: Generate Release Notes Manually

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select the target branch'
        required: true
        default: 'main'
        type: string

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Set Report Date Time
        id: datetime
        run: echo "DATESTAMP=$(date +"%Y-%m-%d")" >> "$GITHUB_OUTPUT"
        env:
          TZ: America/Phoenix

      - name: Generate Release Notes File
        id: release_notes
        run: |
          mkdir -p release-notes
          FILE="release-notes/release-notes-${{ github.event.inputs.target_branch }}-${{ steps.datetime.outputs.DATESTAMP }}.md"
          echo "# 📄 Release Notes" > $FILE
          echo "" >> $FILE
          echo "- 📅 Date: ${{ steps.datetime.outputs.DATESTAMP }}" >> $FILE
          echo "- 🌿 Branch: ${{ github.event.inputs.target_branch }}" >> $FILE
          echo "" >> $FILE
          echo "## 🚀 Changes" >> $FILE
          echo "- Example: Added feature X" >> $FILE
          echo "- Example: Fixed bug Y" >> $FILE

      - name: Upload release notes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes/
          